spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password:   
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 